version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: gb
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  my_api:
    build: auth_api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://gb:123@postgres:5432/db
    ports:
      - "8000:8000"

volumes:
  postgres_data: